//! `KindModel`s → the text of `generated.rs`. Strings are emitted with `{:?}`, which
//! produces valid Rust string literals.

use std::fmt::Write;

use anyhow::{Result, bail};
use nutsh_catalog::ColumnKind;

use super::model::{
    ColumnModel, DetailSectionModel, FieldKind, FieldModel, KindModel, NamespaceModel,
};
use super::nav::GroupModel;
use super::pages::PagesFile;

const METHODS: &[&str] = &["Get", "Post", "Put", "Patch", "Delete"];
const RETURNS: &[&str] = &["Task", "Payload", "None"];
const DANGERS: &[&str] = &["None", "Low", "Medium", "High"];
const CONFIRMS: &[&str] = &["None", "Yes", "TypeName"];

pub fn render(
    namespaces: &[NamespaceModel],
    kinds: &[KindModel],
    groups: &[GroupModel],
    // How many of `groups` came from `nav.toml` rather than from a namespace.
    curated_groups: usize,
    pages: &PagesFile,
) -> Result<String> {
    let mut s = String::new();
    writeln!(
        s,
        "// @generated by `cargo xtask gen-catalog` from specs/. Do not edit."
    )?;
    writeln!(
        s,
        "use crate::{{{}}};",
        imports(kinds, groups, pages).join(", ")
    )?;
    writeln!(s)?;
    writeln!(s, "pub static NAMESPACES: &[Namespace] = &[")?;
    for n in namespaces {
        writeln!(
            s,
            "    Namespace {{ name: {:?}, version: {:?}, preview: {}, versions: &{:?} }},",
            n.name, n.version, n.preview, n.versions
        )?;
    }
    writeln!(s, "];")?;
    writeln!(s)?;
    writeln!(s, "pub static KINDS: &[Kind] = &[")?;
    for k in kinds {
        writeln!(s, "    Kind {{")?;
        writeln!(s, "        id: {:?},", k.id)?;
        writeln!(s, "        namespace: {:?},", k.namespace)?;
        writeln!(s, "        version: {:?},", k.version)?;
        writeln!(s, "        since: {:?},", k.since)?;
        writeln!(s, "        display: {:?},", k.display)?;
        writeln!(s, "        aliases: &{:?},", k.aliases)?;
        writeln!(s, "        category: {:?},", k.category)?;
        writeln!(s, "        poll_secs: {},", k.poll_secs)?;
        writeln!(s, "        list_path: {:?},", k.list_path)?;
        writeln!(s, "        get_path: {},", opt(&k.get_path))?;
        writeln!(s, "        schema: {:?},", k.schema)?;
        let p = &k.list_params;
        writeln!(
            s,
            "        list_params: ListParams {{ page: {}, limit: {}, filter: {}, orderby: {}, select: {}, expand: {}, required: {} }},",
            p.page, p.limit, p.filter, p.orderby, p.select, p.expand, p.required
        )?;
        writeln!(s, "        orderby: {},", opt(&k.orderby))?;
        writeln!(s, "        probe_by: {},", opt(&k.probe_by))?;
        writeln!(
            s,
            "        max_rows: {},",
            match k.max_rows {
                Some(n) => format!("Some({n})"),
                None => "None".to_string(),
            }
        )?;
        writeln!(s, "        select: {},", opt(&k.select))?;
        writeln!(s, "        parent: {},", opt(&k.parent))?;
        writeln!(s, "        actions: &[")?;
        for a in &k.actions {
            if !METHODS.contains(&a.method.as_str()) {
                bail!("unknown method {} on {}", a.method, k.id);
            }
            if !RETURNS.contains(&a.returns.as_str()) {
                bail!("unknown return shape {} on {} {}", a.returns, k.id, a.name);
            }
            if !DANGERS.contains(&a.danger.as_str()) {
                bail!("unknown danger {} on {} {}", a.danger, k.id, a.name);
            }
            if !CONFIRMS.contains(&a.confirm.as_str()) {
                bail!("unknown confirm {} on {} {}", a.confirm, k.id, a.name);
            }
            writeln!(
                s,
                "            Action {{ name: {:?}, path: {:?}, method: Method::{}, needs_etag: {}, needs_body: {}, takes_body: {}, returns: ActionReturn::{}, scope: &{:?}, roles: &{:?}, key: {:?}, label: {:?}, danger: Danger::{}, confirm: ConfirmKind::{}, order: {}, hidden: {}, body: {}, form: &[{}], rate: RateLimit {{ count: {}, per_secs: {} }} }},",
                a.name,
                a.path,
                a.method,
                a.needs_etag,
                a.needs_body,
                a.takes_body,
                a.returns,
                a.scope,
                a.roles,
                a.key,
                a.label,
                a.danger,
                a.confirm,
                a.order,
                a.hidden,
                opt(&a.body),
                fields(&a.form),
                a.rate.count,
                a.rate.per_secs,
            )?;
        }
        writeln!(s, "        ],")?;
        writeln!(s, "        action_kind: {},", opt(&k.action_kind))?;
        writeln!(s, "        action_parents: &{:?},", k.action_parents)?;
        writeln!(
            s,
            "        rate: RateLimit {{ count: {}, per_secs: {} }},",
            k.rate.count, k.rate.per_secs
        )?;
        writeln!(s, "        ext_id_key: {:?},", k.ext_id_key)?;
        writeln!(s, "        name_path: {:?},", k.name_path)?;
        writeln!(s, "        warm: {},", k.warm)?;
        write_columns(&mut s, 8, "columns", &k.columns, &k.id)?;
        write_columns(&mut s, 8, "fallback_columns", &k.fallback_columns, &k.id)?;
        write_detail(&mut s, &k.detail, &k.id)?;
        writeln!(s, "        preview: {},", k.preview)?;
        writeln!(s, "        curated: {},", k.curated)?;
        let mut roles = Vec::with_capacity(k.status_roles.len());
        for (word, role) in &k.status_roles {
            if nutsh_catalog::Role::from_name(role).is_none() {
                bail!("unknown role {role} on {}", k.id);
            }
            roles.push(format!("({word:?}, Role::{role})"));
        }
        writeln!(s, "        status_roles: &[{}],", roles.join(", "))?;
        writeln!(s, "    }},")?;
    }
    writeln!(s, "];")?;
    writeln!(s)?;
    write_nav(&mut s, groups, curated_groups)?;
    writeln!(s)?;
    write_pages(&mut s, pages)?;
    Ok(s)
}

/// The sidebar's tree: the curated groups of `nav.toml`, then the generated per-namespace
/// ones, in the order `with_namespace_groups` put them in.
fn write_nav(s: &mut String, groups: &[GroupModel], curated: usize) -> Result<()> {
    writeln!(
        s,
        "/// How many leading groups of `NAV` came from `nav.toml`: what the sidebar's `1`..`9`"
    )?;
    writeln!(s, "/// cover, and where `0` finds the first generated one.")?;
    writeln!(s, "pub const CURATED_GROUPS: usize = {curated};")?;
    writeln!(s)?;
    writeln!(s, "pub static NAV: &[NavGroup] = &[")?;
    for g in groups {
        writeln!(s, "    NavGroup {{ name: {:?}, items: &[", g.name)?;
        for item in &g.items {
            let target = match (&item.kind, &item.page, item.contexts, item.settings) {
                (Some(id), ..) => format!("NavTarget::Kind({id:?})"),
                (_, Some(id), ..) => format!("NavTarget::Page({id:?})"),
                (_, _, true, _) => "NavTarget::Contexts".to_string(),
                (_, _, _, true) => "NavTarget::Settings".to_string(),
                _ => "NavTarget::Missing".to_string(),
            };
            writeln!(
                s,
                "        NavItem {{ label: {:?}, target: {target}, note: {} }},",
                item.label,
                opt(&item.note)
            )?;
        }
        writeln!(s, "    ] }},")?;
    }
    writeln!(s, "];")?;
    Ok(())
}

fn write_pages(s: &mut String, pages: &PagesFile) -> Result<()> {
    writeln!(s, "pub static PAGES: &[PageDef] = &[")?;
    for p in &pages.pages {
        writeln!(s, "    PageDef {{")?;
        writeln!(s, "        id: {:?},", p.id)?;
        writeln!(s, "        title: {:?},", p.title)?;
        writeln!(s, "        row_heights: &{:?},", p.row_heights)?;
        writeln!(s, "        summary: {},", opt(&p.summary))?;
        writeln!(s, "        summary_rows: {},", p.summary_rows)?;
        writeln!(s, "        panes: &[")?;
        for pane in &p.panes {
            writeln!(s, "            PaneDef {{")?;
            writeln!(s, "                title: {:?},", pane.title)?;
            writeln!(s, "                kind: {:?},", pane.kind)?;
            writeln!(s, "                filter: {},", opt(&pane.filter))?;
            writeln!(s, "                orderby: {},", opt(&pane.orderby))?;
            writeln!(
                s,
                "                row: {}, col: {}, weight: {},",
                pane.row, pane.col, pane.weight
            )?;
            writeln!(s, "                empty: {:?},", pane.empty)?;
            write_columns(s, 16, "columns", &pane.columns, &pane.kind)?;
            writeln!(s, "            }},")?;
        }
        writeln!(s, "        ],")?;
        writeln!(s, "    }},")?;
    }
    writeln!(s, "];")?;
    Ok(())
}

/// The names the emitted source uses, sorted. Every one must be read by the output: the
/// catalog builds with `-D warnings`, and an unused import is one. `Field` and `FieldType`
/// therefore join the list only once some action carries a form, and `NavItem`, `NavTarget`
/// and `PaneDef` only once a group has an item or a page has a pane.
fn imports(kinds: &[KindModel], groups: &[GroupModel], pages: &PagesFile) -> Vec<&'static str> {
    let mut names = vec![
        "Action",
        "ActionReturn",
        "Column",
        "ColumnKind",
        "ConfirmKind",
        "Danger",
        "Kind",
        "ListParams",
        "Method",
        "Namespace",
        "NavGroup",
        "PageDef",
        "RateLimit",
        "Role",
    ];
    if kinds
        .iter()
        .any(|k| k.actions.iter().any(|a| !a.form.is_empty()))
    {
        names.extend(["Field", "FieldType"]);
    }
    // Only once some kind carries a detail: the catalog builds with `-D warnings`, and an unused
    // import is one.
    if kinds.iter().any(|k| !k.detail.is_empty()) {
        names.extend(["DetailField", "DetailSection"]);
    }
    if groups.iter().any(|g| !g.items.is_empty()) {
        names.extend(["NavItem", "NavTarget"]);
    }
    if pages.pages.iter().any(|p| !p.panes.is_empty()) {
        names.push("PaneDef");
    }
    names.sort_unstable();
    names
}

fn opt(v: &Option<String>) -> String {
    match v {
        Some(x) => format!("Some({x:?})"),
        None => "None".to_string(),
    }
}

/// `indent` is the column the field name starts in: 8 inside a `Kind`, 16 inside a `PaneDef`,
/// so the generated file stays readable at both depths.
fn write_columns(
    s: &mut String,
    indent: usize,
    field: &str,
    cols: &[ColumnModel],
    id: &str,
) -> Result<()> {
    let pad = " ".repeat(indent);
    writeln!(s, "{pad}{field}: &[")?;
    for c in cols {
        let Some(kind) = ColumnKind::from_name(&c.kind) else {
            bail!("unknown column kind {} on {}", c.kind, id);
        };
        writeln!(
            s,
            "{pad}    Column {{ header: {:?}, path: {:?}, kind: ColumnKind::{} }},",
            c.header,
            c.path,
            kind.as_str()
        )?;
    }
    writeln!(s, "{pad}],")?;
    Ok(())
}

/// The kind's detail sections. One line per section header and one per field, so a reviewer can
/// read a curated detail out of the generated file as easily as out of `curated.toml`.
fn write_detail(s: &mut String, sections: &[DetailSectionModel], id: &str) -> Result<()> {
    writeln!(s, "        detail: &[")?;
    for section in sections {
        writeln!(
            s,
            "            DetailSection {{ title: {:?}, when: {}, fields: &[",
            section.title,
            opt(&section.when)
        )?;
        for f in &section.fields {
            let Some(kind) = ColumnKind::from_name(&f.kind) else {
                bail!("unknown detail field kind {} on {}", f.kind, id);
            };
            writeln!(
                s,
                "                DetailField {{ label: {:?}, path: {:?}, kind: ColumnKind::{}, when: {} }},",
                f.label,
                f.path,
                kind.as_str(),
                opt(&f.when)
            )?;
        }
        writeln!(s, "            ] }},")?;
    }
    writeln!(s, "        ],")?;
    Ok(())
}

/// A `Field` list as one inline expression; empty for an action with no form.
fn fields(fs: &[FieldModel]) -> String {
    fs.iter()
        .map(|f| {
            format!(
                " Field {{ name: {:?}, label: {:?}, ty: {}, required: {}, value: {}, hidden: {} }},",
                f.name,
                f.label,
                field_type(&f.ty),
                f.required,
                opt(&f.value),
                f.hidden
            )
        })
        .collect()
}

fn field_type(t: &FieldKind) -> String {
    match t {
        FieldKind::Text => "FieldType::Text".to_string(),
        FieldKind::Bool => "FieldType::Bool".to_string(),
        FieldKind::Integer => "FieldType::Integer".to_string(),
        FieldKind::Enum(vs) => format!("FieldType::Enum(&{vs:?})"),
        FieldKind::Reference(k) => format!("FieldType::Reference({})", opt(k)),
        FieldKind::Json(seed) => format!("FieldType::Json({seed:?})"),
    }
}
